Resources:
  EdukitAgentStreamEE53CD18:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
      Name: edukit-agent-stream
      RetentionPeriodHours: 24
      StreamEncryption:
        Fn::If:
          - AwsCdkKinesisEncryptedStreamsUnsupportedRegions
          - Ref: AWS::NoValue
          - EncryptionType: KMS
            KeyId: alias/aws/kinesis
    Metadata:
      aws:cdk:path: edukitapp/EdukitAgentStream/Resource
  edukitagentstreamtable089D1B40:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: AgentARN
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: AgentARN
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: edukitapp/edukit-agent-stream-table/Resource
  edukitapplambdarole32FF2AAF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: edukitapp/edukitapp_lambda_role/Resource
  edukitapplambdaroleDefaultPolicy70ADBC12:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
          - Action:
              - kinesis:DescribeStreamSummary
              - kinesis:GetRecords
              - kinesis:GetShardIterator
              - kinesis:ListShards
              - kinesis:SubscribeToShard
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - EdukitAgentStreamEE53CD18
                - Arn
          - Action: kinesis:DescribeStream
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - EdukitAgentStreamEE53CD18
                - Arn
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - edukitagentstreamtable089D1B40
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: edukitapplambdaroleDefaultPolicy70ADBC12
      Roles:
        - Ref: edukitapplambdarole32FF2AAF
    Metadata:
      aws:cdk:path: edukitapp/edukitapp_lambda_role/DefaultPolicy/Resource
  lambdahandler6F0AA224:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5S3BucketA81B0F4D
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5S3VersionKey6A80CAC7
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5S3VersionKey6A80CAC7
      Role:
        Fn::GetAtt:
          - edukitapplambdarole32FF2AAF
          - Arn
      Environment:
        Variables:
          TEST: TEST
      Handler: index.lambda_handler
      Runtime: python3.8
    DependsOn:
      - edukitapplambdaroleDefaultPolicy70ADBC12
      - edukitapplambdarole32FF2AAF
    Metadata:
      aws:cdk:path: edukitapp/lambdahandler/Resource
      aws:asset:path: /Users/franccan/aws-connect-edukit-demo/edukitapp/cdk.out/asset.22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5
      aws:asset:property: Code
  lambdahandlerKinesisEventSourceedukitappEdukitAgentStream652718FBADC403E7:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName:
        Ref: lambdahandler6F0AA224
      BatchSize: 100
      EventSourceArn:
        Fn::GetAtt:
          - EdukitAgentStreamEE53CD18
          - Arn
      StartingPosition: TRIM_HORIZON
    Metadata:
      aws:cdk:path: edukitapp/lambdahandler/KinesisEventSource:edukitappEdukitAgentStream652718FB/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE2VPwU7DMAz9lt1Tj2riwA02wQ2p6vYDbuqN0Map4pSpivLvNClw4fSe7efn5xrq+gHq3TPepdL9sI/aeYJ4DqgHdbryyXFvgnGsWhI3e03qRYTCKrgZvql1LsHPOmRxgx4tBfK5+NUnlb3jYJjESLb2hDYrNpZUvzBa13cQL9iNlEeFJGXQQmzd1ivYuNHopRwrLKkRbddjNS3hwzE0Bd5m1iW0HCrMcQVK6rWG46wHCkcU+lmFuLr9bbx+EYdzSf6O01R+vPL/bkpJbcf2B3iCx92nGFP5mYOxBO2G316Y0t1fAQAA
    Metadata:
      aws:cdk:path: edukitapp/CDKMetadata/Default
Conditions:
  AwsCdkKinesisEncryptedStreamsUnsupportedRegions:
    Fn::Or:
      - Fn::Equals:
          - Ref: AWS::Region
          - cn-north-1
      - Fn::Equals:
          - Ref: AWS::Region
          - cn-northwest-1
Parameters:
  AssetParameters22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5S3BucketA81B0F4D:
    Type: String
    Description: S3 bucket for asset "22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5"
  AssetParameters22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5S3VersionKey6A80CAC7:
    Type: String
    Description: S3 key for asset version "22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5"
  AssetParameters22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5ArtifactHashC62150CA:
    Type: String
    Description: Artifact hash for asset "22a6261630aafb61e9a11e242b94f709488cc6a2d9f42f5e214be19cb93666c5"

